package com.veta.servlets;

import com.veta.dao.ApplicationDAO;
import com.veta.dao.PaymentDAO;
import com.veta.models.Application;
import com.veta.models.Payment;
import javax.servlet.*;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;
import java.io.*;

@WebServlet({"/pdf", "/download"})
public class PdfServlet extends HttpServlet {

    private final PaymentDAO     payDAO = new PaymentDAO();
    private final ApplicationDAO appDAO = new ApplicationDAO();

    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse res)
            throws ServletException, IOException {

        String type = req.getParameter("type"); // receipt | admission | id
        String ref  = req.getParameter("ref");

        res.setContentType("application/pdf");

        try {
            if ("receipt".equals(type) && ref != null) {
                Payment p = payDAO.findByControlNumber(ref);
                res.setHeader("Content-Disposition", "attachment; filename=Receipt_" + ref + ".pdf");
                generateReceiptPdf(res.getOutputStream(), p);

            } else if ("admission".equals(type) && ref != null) {
                Application a = appDAO.findByRef(ref);
                res.setHeader("Content-Disposition", "attachment; filename=AdmissionLetter_" + ref + ".pdf");
                generateAdmissionPdf(res.getOutputStream(), a);

            } else {
                res.sendError(400, "Invalid PDF request.");
            }
        } catch (Exception e) {
            res.sendError(500, "PDF generation error: " + e.getMessage());
        }
    }

    /** Payment receipt PDF using iText */
    private void generateReceiptPdf(OutputStream out, Payment p) throws Exception {
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(doc, out);
        doc.open();

        com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 16,
                com.itextpdf.text.Font.BOLD,
                new com.itextpdf.text.BaseColor(10, 36, 99));

        com.itextpdf.text.Font normalFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 11);

        com.itextpdf.text.Font labelFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 10,
                com.itextpdf.text.Font.BOLD,
                com.itextpdf.text.BaseColor.GRAY);

        // Header
        doc.add(new com.itextpdf.text.Paragraph("VETA COLLEGE TANZANIA", titleFont));
        doc.add(new com.itextpdf.text.Paragraph(
                "Vocational Education & Training Authority\nKinondoni, Dar es Salaam, Tanzania\n+255 22 123 4567 | info@vetacollege.ac.tz",
                labelFont));
        doc.add(com.itextpdf.text.Chunk.NEWLINE);

        // Title
        com.itextpdf.text.Font h2 = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 14, com.itextpdf.text.Font.BOLD);
        doc.add(new com.itextpdf.text.Paragraph("OFFICIAL PAYMENT RECEIPT", h2));
        doc.add(com.itextpdf.text.Chunk.NEWLINE);

        if (p != null) {
            doc.add(new com.itextpdf.text.Paragraph("Control Number : " + p.getControlNumber(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Payer Name     : " + p.getPayerName(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Phone          : " + p.getPayerPhone(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Payment Type   : " + p.getPaymentType(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Amount (TZS)   : " + String.format("%,.2f", p.getAmount()), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Status         : " + p.getStatus(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Date           : " + (p.getPaidAt() != null ? p.getPaidAt() : p.getCreatedAt()), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Academic Year  : " + p.getAcademicYear(), normalFont));
        }
        doc.add(com.itextpdf.text.Chunk.NEWLINE);
        doc.add(new com.itextpdf.text.Paragraph("This is an official receipt generated by VETA College Tanzania.", labelFont));
        doc.close();
    }

    /** Admission letter PDF */
    private void generateAdmissionPdf(OutputStream out, Application a) throws Exception {
        com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        com.itextpdf.text.pdf.PdfWriter.getInstance(doc, out);
        doc.open();

        com.itextpdf.text.Font titleFont = new com.itextpdf.text.Font(
                com.itextpdf.text.Font.FontFamily.HELVETICA, 16,
                com.itextpdf.text.Font.BOLD,
                new com.itextpdf.text.BaseColor(10, 36, 99));

        com.itextpdf.text.Font normalFont  = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 11);
        com.itextpdf.text.Font boldFont    = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 11, com.itextpdf.text.Font.BOLD);
        com.itextpdf.text.Font labelFont   = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 10, com.itextpdf.text.Font.ITALIC, com.itextpdf.text.BaseColor.GRAY);

        doc.add(new com.itextpdf.text.Paragraph("VETA COLLEGE TANZANIA", titleFont));
        doc.add(new com.itextpdf.text.Paragraph("Vocational Education & Training Authority\nKinondoni, Dar es Salaam | +255 22 123 4567", labelFont));
        doc.add(com.itextpdf.text.Chunk.NEWLINE);

        com.itextpdf.text.Font h2 = new com.itextpdf.text.Font(com.itextpdf.text.Font.FontFamily.HELVETICA, 14, com.itextpdf.text.Font.BOLD);
        doc.add(new com.itextpdf.text.Paragraph("ADMISSION LETTER", h2));
        doc.add(com.itextpdf.text.Chunk.NEWLINE);

        if (a != null) {
            doc.add(new com.itextpdf.text.Paragraph("Dear " + a.getFullName() + ",", boldFont));
            doc.add(com.itextpdf.text.Chunk.NEWLINE);
            doc.add(new com.itextpdf.text.Paragraph(
                "We are pleased to inform you that your application to VETA College Tanzania has been " +
                (a.getStatus().equals("APPROVED") ? "APPROVED" : "received and is under review") + ".", normalFont));
            doc.add(com.itextpdf.text.Chunk.NEWLINE);
            doc.add(new com.itextpdf.text.Paragraph("Reference Number : " + a.getRefNumber(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Program Applied  : " + a.getCourseName(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Intake Period    : " + a.getIntakePeriod(), normalFont));
            doc.add(new com.itextpdf.text.Paragraph("Status           : " + a.getStatus(), normalFont));
            doc.add(com.itextpdf.text.Chunk.NEWLINE);
            doc.add(new com.itextpdf.text.Paragraph(
                "Please proceed to the Payments page to generate a Control Number and pay your application fee of TZS 20,000 " +
                "to confirm your place. For inquiries, contact admissions@vetacollege.ac.tz or +255 754 000 111.", normalFont));
        }
        doc.add(com.itextpdf.text.Chunk.NEWLINE);
        doc.add(new com.itextpdf.text.Paragraph("Yours faithfully,", normalFont));
        doc.add(new com.itextpdf.text.Paragraph("Mrs. Salome Waweru", boldFont));
        doc.add(new com.itextpdf.text.Paragraph("Registrar, VETA College Tanzania", labelFont));
        doc.close();
    }
}
